apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-deployment
  labels:
    app: messagebird-exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagebird-exercise
  template:
    metadata:
      labels:
        app: messagebird-exercise
    spec:
      containers:
      - name: mb-exercise
        image: 313368690603.dkr.ecr.eu-west-1.amazonaws.com/homer-and-covilha:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mb-service
spec:
  selector:
    app: messagebird-exercise
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
